### ISSUE TITLE
Typo when game is won

### ISSUE THREAD

**Issue by MagicFab** [darthjoey91/Hangman-Android#3]
When the game is won a message appears "You Wins!". I believe it should be "You Win!".

**Comment by darthjoey91** [comment]
It's intentionally bad. Inspired by old games as listed [here](http://tvtropes.org/pmwiki/pmwiki.php/Main/AWinnerIsYou) combined with [this](http://tvtropes.org/pmwiki/pmwiki.php/Main/IntentionalEngrishForFunny).

**Comment by MagicFab** [comment]
:D Excellent, I hesitated before filing this, so, TIL this.
